"""add_template_columns

Revision ID: 291f1327838b
Revises: 11820f8dfbc0
Create Date: 2025-08-06 03:01:10.206059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291f1327838b'
down_revision: Union[str, None] = '11820f8dfbc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('apprentice', 'mentor', 'admin', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('apprentice', 'mentor', 'admin', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
