"""Added templating

Revision ID: 49f18c57a26a
Revises: d0b97fc8fa65
Create Date: 2025-05-28 22:31:35.303630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f18c57a26a'
down_revision: Union[str, None] = 'd0b97fc8fa65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_template_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('question_id', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['assessment_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_answers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_drafts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assessment_drafts', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('assessment_drafts', sa.Column('template_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'assessment_drafts', 'assessment_templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assessment_drafts', type_='foreignkey')
    op.drop_column('assessment_drafts', 'template_id')
    op.drop_column('assessment_drafts', 'score')
    op.drop_table('assessment_answers')
    op.drop_table('assessment_template_questions')
    op.drop_table('assessment_templates')
    # ### end Alembic commands ###
