"""add mentor_apprentice

Revision ID: 890307c1327d
Revises: 870e2989128b
Create Date: 2025-05-27 19:37:01.430166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890307c1327d'
down_revision: Union[str, None] = '870e2989128b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mentor_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mentor_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
