"""add_answers_to_assessment_drafts

Revision ID: 89fc120338ae
Revises: 1f5966bf6735
Create Date: 2025-08-04 04:13:16.619940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89fc120338ae'
down_revision: Union[str, None] = '1f5966bf6735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_drafts', sa.Column('answers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_drafts', 'answers')
    # ### end Alembic commands ###
