"""Add created_at to users

Revision ID: d0b97fc8fa65
Revises: 6155ad3585cf
Create Date: 2025-05-27 22:46:51.301495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b97fc8fa65'
down_revision: Union[str, None] = '6155ad3585cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_drafts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('apprentice_id', sa.String(), nullable=False),
    sa.Column('last_question_id', sa.String(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apprentice_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assessments', sa.Column('apprentice_id', sa.String(), nullable=False))
    op.add_column('assessments', sa.Column('answers', sa.JSON(), nullable=False))
    op.add_column('assessments', sa.Column('scores', sa.JSON(), nullable=True))
    op.add_column('assessments', sa.Column('recommendation', sa.String(), nullable=True))
    op.add_column('assessments', sa.Column('category', sa.String(), nullable=True))
    op.add_column('assessments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_constraint(op.f('assessments_user_id_fkey'), 'assessments', type_='foreignkey')
    op.create_foreign_key(None, 'assessments', 'users', ['apprentice_id'], ['id'])
    op.drop_column('assessments', 'title')
    op.drop_column('assessments', 'user_id')
    op.drop_column('assessments', 'score')
    op.drop_column('assessments', 'feedback')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.add_column('assessments', sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assessments', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('assessments', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.create_foreign_key(op.f('assessments_user_id_fkey'), 'assessments', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.drop_column('assessments', 'created_at')
    op.drop_column('assessments', 'category')
    op.drop_column('assessments', 'recommendation')
    op.drop_column('assessments', 'scores')
    op.drop_column('assessments', 'answers')
    op.drop_column('assessments', 'apprentice_id')
    op.drop_table('assessment_drafts')
    # ### end Alembic commands ###
